"""Writer agent — hybrid-retrieval claim gathering, LLM synthesis, cross-section dedup."""

from __future__ import annotations

import hashlib
import json
import logging
import re

from researchops.agents.base import AgentBase
from researchops.apps.research.adapters import NOISE_PATTERNS
from researchops.apps.research.prompts import WRITER_CONCLUSION, WRITER_SECTION
from researchops.apps.research.schemas import PlanOutput, SourceNotes
from researchops.core.context import RunContext
from researchops.core.state import AgentResult, Stage
from researchops.core.tools.builtins import reset_citations
from researchops.utils import load_all_notes, load_sources

logger = logging.getLogger(__name__)

_HEADING_CN_MAP: list[tuple[list[str], str]] = [
    (["introduction", "intro"], "引言"),
    (["key components", "overview", "概述"], "概述与关键组成"),
    (["current state", "state of research", "研究现状"], "研究现状"),
    (["challenges", "limitations", "挑战", "局限"], "主要挑战与局限"),
    (["future", "directions", "未来", "方向"], "未来方向"),
    (["conclusion", "summary", "总结"], "总结"),
    (["references", "参考"], "参考来源"),
    (["disagreements", "conflicts", "分歧"], "分歧与争议"),
    (["note", "说明"], "说明"),
    (["evidence gap", "证据缺口"], "证据缺口"),
]

_DISCARD_PATTERNS = [
    "not a research claim", "not a claim", "this is css", "this is javascript",
    "corrupted", "encoded data", "not meaningful", "cannot extract",
    "padding:", "margin:", "function(", "queryselector", "addeventlistener",
    "stylesheet", "doctype", "viewport", "meta charset",
]

_MAX_SENTENCE_LEN = 260
_MAX_CLAIMS_PER_SECTION = 8
_SOURCE_CAP_RATIO = 0.35


def _is_cjk_topic(topic: str) -> bool:
    if not topic:
        return False
    cjk_count = sum(1 for c in topic if "\u4e00" <= c <= "\u9fff" or "\u3400" <= c <= "\u4dbf")
    return cjk_count / max(1, len(topic)) >= 0.3


def _localize_heading(heading: str, is_cjk: bool) -> str:
    if not is_cjk:
        cleaned = re.sub(r"[\u4e00-\u9fff\u3400-\u4dbf]+", "", heading).strip()
        cleaned = re.sub(r"\s{2,}", " ", cleaned)
        return cleaned if cleaned else heading
    lower = heading.lower()
    for keywords, cn_heading in _HEADING_CN_MAP:
        if any(kw in lower for kw in keywords):
            return cn_heading
    return heading


def _clean_rq_heading(heading: str) -> str:
    heading = re.sub(r"^(Is|Are|What|How|Why|Does|Do|Can|Could|Should)\s+", "", heading, flags=re.IGNORECASE)
    heading = re.sub(r"\s+and\s+what\s+are\s+", " — ", heading, flags=re.IGNORECASE)
    heading = heading.strip().rstrip("?")
    if heading:
        heading = heading[0].upper() + heading[1:]
    return heading


def _is_noisy_claim(text: str) -> bool:
    lower = text.lower()
    return (
        any(p in lower for p in NOISE_PATTERNS)
        or any(p in lower for p in _DISCARD_PATTERNS)
    )


def _normalize(text: str) -> str:
    return re.sub(r"[\s\d\W]+", "", text.lower())


def _truncate_sentence(sentence: str, max_len: int = _MAX_SENTENCE_LEN) -> str:
    if len(sentence) <= max_len:
        return sentence
    marker_match = re.search(r"\s*\[@\w+\]\s*$", sentence)
    marker = marker_match.group(0) if marker_match else ""
    body = sentence[: len(sentence) - len(marker)] if marker else sentence
    budget = max_len - len(marker) - 3
    return body[:budget].rstrip() + "..." + marker


class WriterAgent(AgentBase):
    name = "writer"

    def execute(self, ctx: RunContext) -> AgentResult:
        ctx.trace.log(stage="WRITE", agent=self.name, action="start")
        reset_citations()

        plan = PlanOutput.model_validate(
            json.loads((ctx.run_dir / "plan.json").read_text(encoding="utf-8"))
        )
        sources = load_sources(ctx.run_dir)
        all_notes = load_all_notes(ctx.run_dir)
        is_cjk = _is_cjk_topic(plan.topic)
        is_deep = ctx.config.mode.value == "deep"

        retriever = ctx.shared.get("retriever")
        at_max_rounds = ctx.state.collect_rounds >= ctx.config.max_collect_rounds

        evidence_map = self._build_evidence_map(plan, retriever, all_notes, ctx)
        emap_path = ctx.run_dir / "evidence_map.json"
        emap_path.write_text(json.dumps(evidence_map, indent=2), encoding="utf-8")

        lines: list[str] = []
        report_index: list[dict] = []
        unsupported_sections = 0
        evidence_gap_sections: list[str] = []
        used_claims_global: set[str] = set()

        lines.append(f"# {plan.topic}\n")
        gen_label = "*ResearchOps Agent 自动生成*" if is_cjk else "*Generated by ResearchOps Agent*"
        lines.append(f"{gen_label}\n")

        section_summaries: list[dict] = []

        for section in plan.outline:
            heading = _localize_heading(section.heading, is_cjk)
            heading = _clean_rq_heading(heading)

            is_conclusion = section.heading.lower() in (
                "conclusion", "summary", "总结",
            )

            if is_conclusion:
                lines.append(f"\n## {heading}\n")
                conclusion_text, idx_entries = self._write_conclusion(
                    section_summaries, ctx, plan.topic, is_cjk,
                )
                if conclusion_text:
                    lines.append(f"{conclusion_text}\n")
                    report_index.extend(idx_entries)
                else:
                    gap_text = self._write_evidence_gap(heading, section.rq_refs, is_cjk)
                    lines.append(f"{gap_text}\n")
                continue

            lines.append(f"\n## {heading}\n")

            emap_entry = evidence_map.get(section.heading, {})
            selected = self._gather_claims_for_section(
                section.rq_refs, retriever, all_notes, heading, used_claims_global,
            )

            if selected and (emap_entry.get("source_count", 0) > 0 or not emap_entry):
                for _, _, cid in selected:
                    used_claims_global.add(cid)

                overview, bullets, trend_block, idx_entries = self._write_section(
                    selected, ctx, heading, is_cjk, is_deep,
                )

                if overview:
                    lines.append(f"{overview}\n")
                if bullets:
                    lines.append("")
                    for b in bullets:
                        lines.append(b)
                    lines.append("")
                if trend_block:
                    lines.append(f"{trend_block}\n")
                report_index.extend(idx_entries)

                section_summaries.append({
                    "heading": heading,
                    "claims": [(t, s) for t, s, _ in selected[:3]],
                })
            else:
                unsupported_sections += 1
                evidence_gap_sections.append(heading)
                gap_text = self._write_evidence_gap(heading, section.rq_refs, is_cjk)
                lines.append(f"{gap_text}\n")
                report_index.append({
                    "hash": hashlib.sha256(gap_text.encode()).hexdigest()[:12],
                    "text": gap_text[:200],
                    "source_ids": [], "claim_ids": [], "evidence_gap": True,
                })

        if ctx.shared.get("evidence_limited"):
            note_heading = "说明" if is_cjk else "Note"
            lines.append(f"\n## {note_heading}\n")
            note = ("*由于离线模式（allow_net=false），证据收集受限。*\n" if is_cjk
                    else "*Evidence collection limited due to offline mode (allow_net=false).*\n")
            lines.append(note)

        if ctx.shared.get("has_conflicts"):
            self._append_conflicts_section(lines, ctx, is_cjk)

        ref_heading = "参考来源" if is_cjk else "References"
        lines.append(f"\n## {ref_heading}\n")
        seen_refs: set[str] = set()
        for src in sources:
            ref_key = f"{src.title}|{src.domain}"
            if ref_key in seen_refs:
                continue
            seen_refs.add(ref_key)
            lines.append(f"- [@{src.source_id}] {src.title or src.url} ({src.domain})")

        report_path = ctx.run_dir / "report.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")
        index_path = ctx.run_dir / "report_index.json"
        index_path.write_text(json.dumps({"entries": report_index}, indent=2), encoding="utf-8")

        if unsupported_sections > 0 and ctx.config.allow_net and not at_max_rounds:
            ctx.state.incomplete_sections = evidence_gap_sections
            return AgentResult(
                success=False,
                message=f"Report written but {unsupported_sections} sections lack evidence",
                rollback_to=Stage.COLLECT,
            )

        if evidence_gap_sections:
            ctx.state.incomplete_sections = evidence_gap_sections

        ctx.trace.log(
            stage="WRITE", agent=self.name, action="complete",
            output_summary=f"Report: {len(lines)} lines, {len(report_index)} indexed entries",
        )
        return AgentResult(success=True, message="Report written with traceability index")

    # ------------------------------------------------------------------
    # Claim gathering with hybrid retrieval + cross-section dedup
    # ------------------------------------------------------------------

    def _gather_claims_for_section(
        self, rq_refs: list[str], retriever, all_notes: dict[str, SourceNotes],
        heading: str, used_claims: set[str],
    ) -> list[tuple[str, str, str]]:
        raw_claims: list[tuple[str, str, str]] = []

        if retriever and rq_refs:
            for rq_ref in rq_refs:
                query = f"{heading} {rq_ref}"
                retrieved = retriever.retrieve(query, top_k=12)
                for rc in retrieved:
                    cid = rc.get("claim_id", "")
                    raw_claims.append((rc.get("text", ""), rc.get("source_id", ""), cid))
            for rq_ref in rq_refs:
                rq_claims = retriever.retrieve_for_rq(rq_ref, top_k=8)
                for rc in rq_claims:
                    cid = rc.get("claim_id", "")
                    raw_claims.append((rc.get("text", ""), rc.get("source_id", ""), cid))
        else:
            raw_claims = self._claims_for_section(rq_refs, all_notes)

        # Deduplicate + filter noisy + cross-section dedup (allow reuse max 2x)
        filtered: list[tuple[str, str, str]] = []
        seen_norms: set[str] = set()
        for claim_text, source_id, claim_id in raw_claims:
            if _is_noisy_claim(claim_text):
                continue
            norm = _normalize(claim_text)
            if norm in seen_norms:
                continue
            seen_norms.add(norm)
            # Cross-section dedup: skip claims used in 2+ previous sections
            if claim_id in used_claims:
                continue
            filtered.append((claim_text, source_id, claim_id))

        # Source diversity cap
        source_counts: dict[str, int] = {}
        max_per_source = max(1, int(_MAX_CLAIMS_PER_SECTION * _SOURCE_CAP_RATIO))
        selected: list[tuple[str, str, str]] = []
        for claim_text, source_id, claim_id in filtered:
            if len(selected) >= _MAX_CLAIMS_PER_SECTION:
                break
            cnt = source_counts.get(source_id, 0)
            if cnt >= max_per_source:
                continue
            source_counts[source_id] = cnt + 1
            selected.append((claim_text, source_id, claim_id))

        if not selected and filtered:
            selected = filtered[:_MAX_CLAIMS_PER_SECTION]
        return selected

    # ------------------------------------------------------------------
    # Section writing (LLM or template-based)
    # ------------------------------------------------------------------

    def _write_section(
        self, claims: list[tuple[str, str, str]], ctx: RunContext,
        heading: str, is_cjk: bool, is_deep: bool,
    ) -> tuple[str, list[str], str, list[dict]]:
        idx_entries: list[dict] = []

        if ctx.reasoner.is_llm:
            overview, bullets, trend_block, idx_entries = self._llm_write_section(
                claims, ctx, heading, is_cjk, is_deep,
            )
            if overview or bullets:
                return overview, bullets, trend_block, idx_entries

        # Fallback: template-based
        overview_sentences: list[str] = []
        for claim_text, source_id, claim_id in claims[:3]:
            sentence = _truncate_sentence(f"{claim_text} [@{source_id}]")
            overview_sentences.append(sentence)
            idx_entries.append({
                "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                "text": claim_text[:200], "source_ids": [source_id], "claim_ids": [claim_id],
            })

        bullets: list[str] = []
        for claim_text, source_id, claim_id in claims[:6]:
            bullet = _truncate_sentence(f"- {claim_text} [@{source_id}]")
            bullets.append(bullet)
            idx_entries.append({
                "hash": hashlib.sha256(bullet.encode()).hexdigest()[:12],
                "text": claim_text[:200], "source_ids": [source_id], "claim_ids": [claim_id],
            })

        return " ".join(overview_sentences), bullets, "", idx_entries

    def _llm_write_section(
        self, claims: list[tuple[str, str, str]], ctx: RunContext,
        heading: str, is_cjk: bool, is_deep: bool,
    ) -> tuple[str, list[str], str, list[dict]]:
        idx_entries: list[dict] = []
        claims_block = "\n".join(f"[{sid}] {text[:200]}" for text, sid, cid in claims)
        lang = "Chinese" if is_cjk else "English"
        deep_instruction = (
            "3. TRENDS paragraph (2-3 sentences) comparing approaches or noting limitations. "
            "Every sentence must end with [@source_id]." if is_deep else ""
        )

        sys_msg, user_msg = WRITER_SECTION.render(
            heading=heading, lang=lang, claims_block=claims_block,
            deep_instruction=deep_instruction,
        )

        try:
            raw = ctx.reasoner.complete_text(user_msg, context=sys_msg, trace=ctx.trace)
            overview, bullets, trend_block = self._parse_llm_section_output(raw)

            if not re.search(r"\[@\w+\]", overview) and claims:
                overview = ""
            valid_bullets = [b for b in bullets if re.search(r"\[@\w+\]", b)]
            if not valid_bullets and not overview:
                return "", [], "", []

            for sentence in re.split(r"(?<=[.!?。！？])\s*", overview):
                sentence = sentence.strip()
                if len(sentence) > 20:
                    marker_match = re.search(r"\[@(\w+)\]", sentence)
                    sid = marker_match.group(1) if marker_match else ""
                    cid = next((c for _, s, c in claims if s == sid), "")
                    idx_entries.append({
                        "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                        "text": sentence[:200],
                        "source_ids": [sid] if sid else [],
                        "claim_ids": [cid] if cid else [],
                    })

            for b in valid_bullets:
                marker_match = re.search(r"\[@(\w+)\]", b)
                sid = marker_match.group(1) if marker_match else ""
                cid = next((c for _, s, c in claims if s == sid), "")
                idx_entries.append({
                    "hash": hashlib.sha256(b.encode()).hexdigest()[:12],
                    "text": b[:200],
                    "source_ids": [sid] if sid else [],
                    "claim_ids": [cid] if cid else [],
                })

            return overview, valid_bullets, trend_block, idx_entries
        except Exception as exc:
            logger.warning("LLM section write failed for '%s': %s", heading, exc)
            return "", [], "", []

    def _parse_llm_section_output(self, raw: str) -> tuple[str, list[str], str]:
        overview, bullets, trend_block = "", [], ""
        if "OVERVIEW:" in raw:
            parts = raw.split("OVERVIEW:", 1)[1]
            if "BULLETS:" in parts:
                overview = parts.split("BULLETS:", 1)[0].strip()
                rest = parts.split("BULLETS:", 1)[1]
                if "TRENDS:" in rest:
                    bullet_text = rest.split("TRENDS:", 1)[0]
                    trend_block = rest.split("TRENDS:", 1)[1].strip()
                else:
                    bullet_text = rest
                for line in bullet_text.strip().splitlines():
                    line = line.strip()
                    if line.startswith("- "):
                        bullets.append(line)
            else:
                overview = parts.strip()
        else:
            para_lines, bullet_lines = [], []
            for line in raw.strip().splitlines():
                line = line.strip()
                if line.startswith("- "):
                    bullet_lines.append(line)
                elif len(line) > 30:
                    para_lines.append(line)
            overview = " ".join(para_lines[:4])
            bullets = bullet_lines
        return overview, bullets, trend_block

    # ------------------------------------------------------------------
    # Conclusion synthesis
    # ------------------------------------------------------------------

    def _write_conclusion(
        self, section_summaries: list[dict], ctx: RunContext,
        topic: str, is_cjk: bool,
    ) -> tuple[str, list[dict]]:
        if not section_summaries:
            return "", []

        idx_entries: list[dict] = []

        if ctx.reasoner.is_llm:
            text, idx_entries = self._llm_write_conclusion(
                section_summaries, ctx, topic, is_cjk,
            )
            if text:
                return text, idx_entries

        parts: list[str] = []
        for sec in section_summaries:
            for claim_text, source_id in sec["claims"][:1]:
                sentence = _truncate_sentence(f"{claim_text} [@{source_id}]")
                parts.append(sentence)
                idx_entries.append({
                    "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                    "text": claim_text[:200],
                    "source_ids": [source_id],
                    "claim_ids": [],
                })
        return " ".join(parts), idx_entries

    def _llm_write_conclusion(
        self, section_summaries: list[dict], ctx: RunContext,
        topic: str, is_cjk: bool,
    ) -> tuple[str, list[dict]]:
        summary_parts: list[str] = []
        for sec in section_summaries:
            claims_str = "; ".join(
                f"{t[:150]} [@{s}]" for t, s in sec["claims"][:2]
            )
            summary_parts.append(f"- {sec['heading']}: {claims_str}")
        sections_summary = "\n".join(summary_parts)
        lang = "Chinese" if is_cjk else "English"

        sys_msg, user_msg = WRITER_CONCLUSION.render(
            topic=topic, lang=lang, sections_summary=sections_summary,
        )
        try:
            raw = ctx.reasoner.complete_text(user_msg, context=sys_msg, trace=ctx.trace)
            text = raw.strip()
            if not re.search(r"\[@\w+\]", text):
                return "", []

            idx_entries: list[dict] = []
            for sentence in re.split(r"(?<=[.!?。！？])\s*", text):
                sentence = sentence.strip()
                if len(sentence) > 20:
                    marker = re.search(r"\[@(\w+)\]", sentence)
                    sid = marker.group(1) if marker else ""
                    idx_entries.append({
                        "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                        "text": sentence[:200],
                        "source_ids": [sid] if sid else [],
                        "claim_ids": [],
                    })
            return text, idx_entries
        except Exception as exc:
            logger.warning("LLM conclusion write failed: %s", exc)
            return "", []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _write_evidence_gap(self, heading: str, rq_refs: list[str], is_cjk: bool) -> str:
        rq_list = "、".join(rq_refs) if rq_refs else "未知"
        if is_cjk:
            return (f"**证据缺口**：本节（{heading}）相关的研究问题（{rq_list}）"
                    f"在当前检索范围内证据不足。建议补充该领域的综述论文或最新会议论文。")
        rq_list_en = ", ".join(rq_refs) if rq_refs else "unknown"
        return (f"**Evidence Gap**: This section ({heading}) covering ({rq_list_en}) "
                f"has insufficient evidence. Add survey papers or recent conference papers.")

    def _append_conflicts_section(self, lines: list[str], ctx: RunContext, is_cjk: bool) -> None:
        conf_heading = "分歧与争议" if is_cjk else "Disagreements and Conflicts"
        lines.append(f"\n## {conf_heading}\n")
        conflicts_path = ctx.run_dir / "qa_conflicts.json"
        if conflicts_path.exists():
            try:
                cdata = json.loads(conflicts_path.read_text(encoding="utf-8"))
                for conflict in cdata.get("conflicts", [])[:3]:
                    rq = conflict.get("rq_id", "unknown")
                    lines.append(
                        f"- **{rq}**: {conflict.get('support_count', 0)} supporting vs "
                        f"{conflict.get('oppose_count', 0)} opposing claims\n"
                    )
            except Exception:
                lines.append("- Conflicting evidence was detected across sources.\n")
        else:
            lines.append("- Conflicting evidence was detected across sources.\n")

    def _build_evidence_map(
        self, plan: PlanOutput, retriever, all_notes: dict[str, SourceNotes], ctx: RunContext,
    ) -> dict:
        evidence_map: dict = {}
        checklist = plan.coverage_checklist

        for section in plan.outline:
            claims_data = self._gather_claims_for_section(
                section.rq_refs, retriever, all_notes, section.heading, set(),
            )
            source_ids = list({sid for _, sid, _ in claims_data})
            matched_buckets: list[str] = []
            for bucket in checklist:
                bid = bucket.get("bucket_id", "")
                bname = bucket.get("bucket_name", "").lower()
                if bname and bname in section.heading.lower():
                    matched_buckets.append(bid)

            evidence_map[section.heading] = {
                "bucket_ids": matched_buckets,
                "claims": [{"claim_id": cid, "source_id": sid, "text": text[:200]}
                           for text, sid, cid in claims_data[:_MAX_CLAIMS_PER_SECTION]],
                "source_count": len(source_ids),
                "diversity_ok": len(source_ids) >= max(1, ctx.config.target_sources_per_bucket // 2),
            }
        return evidence_map

    def _claims_for_section(
        self, rq_refs: list[str], all_notes: dict[str, SourceNotes],
    ) -> list[tuple[str, str, str]]:
        results: list[tuple[str, str, str]] = []
        for src_id, notes in all_notes.items():
            for claim in notes.claims:
                if not rq_refs or any(r in claim.supports_rq for r in rq_refs):
                    results.append((claim.text, src_id, claim.claim_id))
        return results
