from __future__ import annotations

import hashlib
import json
from pathlib import Path

from researchops.agents.base import AgentBase, RunContext
from researchops.models import AgentResult, PlanOutput, Source, SourceNotes
from researchops.tools.cite import reset_citations


class WriterAgent(AgentBase):
    name = "writer"

    def execute(self, ctx: RunContext) -> AgentResult:
        ctx.trace.log(stage="WRITE", agent=self.name, action="start")
        reset_citations()

        plan = PlanOutput.model_validate(
            json.loads((ctx.run_dir / "plan.json").read_text(encoding="utf-8"))
        )
        sources = self._load_sources(ctx.run_dir)
        all_notes = self._load_all_notes(ctx.run_dir)

        lines: list[str] = []
        report_index: list[dict] = []

        lines.append(f"# {plan.topic}\n")
        lines.append("*Generated by ResearchOps Agent*\n")

        for section in plan.outline:
            lines.append(f"\n## {section.heading}\n")

            relevant_claims = self._claims_for_section(section.rq_refs, all_notes)
            if relevant_claims:
                for claim_text, source_id, claim_id in relevant_claims[:5]:
                    marker = f"[@{source_id}]"
                    sentence = f"{claim_text} {marker}"
                    lines.append(f"{sentence}\n")

                    report_index.append({
                        "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                        "text": claim_text[:200],
                        "source_ids": [source_id],
                        "claim_ids": [claim_id],
                    })
                lines.append("")
            else:
                sentence = "Further research is needed on this topic."
                lines.append(f"{sentence}\n")
                report_index.append({
                    "hash": hashlib.sha256(sentence.encode()).hexdigest()[:12],
                    "text": sentence,
                    "source_ids": [],
                    "claim_ids": [],
                })

        lines.append("\n## References\n")
        for src in sources:
            lines.append(f"- [@{src.source_id}] {src.title or src.url} ({src.domain})")

        report_path = ctx.run_dir / "report.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")

        index_path = ctx.run_dir / "report_index.json"
        index_path.write_text(
            json.dumps({"entries": report_index}, indent=2), encoding="utf-8"
        )

        ctx.trace.log(
            stage="WRITE",
            agent=self.name,
            action="complete",
            output_summary=f"Report: {len(lines)} lines, {len(report_index)} indexed entries",
        )
        return AgentResult(success=True, message="Report written with traceability index")

    def _load_sources(self, run_dir: Path) -> list[Source]:
        path = run_dir / "sources.jsonl"
        if not path.exists():
            return []
        sources = []
        for line in path.read_text(encoding="utf-8").strip().splitlines():
            if line.strip():
                sources.append(Source.model_validate(json.loads(line)))
        return sources

    def _load_all_notes(self, run_dir: Path) -> dict[str, SourceNotes]:
        notes_dir = run_dir / "notes"
        result: dict[str, SourceNotes] = {}
        if not notes_dir.exists():
            return result
        for f in sorted(notes_dir.glob("*.json")):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                notes = SourceNotes.model_validate(data)
                result[notes.source_id] = notes
            except Exception:
                continue
        return result

    def _claims_for_section(
        self, rq_refs: list[str], all_notes: dict[str, SourceNotes]
    ) -> list[tuple[str, str, str]]:
        results: list[tuple[str, str, str]] = []
        for src_id, notes in all_notes.items():
            for claim in notes.claims:
                if not rq_refs or any(r in claim.supports_rq for r in rq_refs):
                    results.append((claim.text, src_id, claim.claim_id))
        return results
